version: 2

models:
  - name: bronze_customers
    description: customer details

    columns:
      - name: customer_id
        description: primary key for the customer dimension
        tests:
          - unique:
              config:
                severity: warn
                warn_if: ">10"
          - not_null
        
      - name: first_name
        description: first name of the customer
        tests:
          - not_null
      - name: last_name
        description: last name for the customer

  - name: bronze_products
    description: product details

    columns:
      - name: product_id
        description: primary key for the product
        tests:
          - unique:
              config:
                severity: warn
                warn_if: ">10"
          - not_null
      - name: price
        description: price of the product
        tests:
          - not_null


  - name: bronze_orders
    description: dimension table for order table containing order details

    columns:
      - name: order_id
        description: primary for the order table
        tests:
          - unique:
              config:
                severity: warn
                warn_if: ">10"
          - not_null

      - name: customer_id
        description: foreign key for customer table
        tests:
          - not_null

      - name: product_id
        description: foreign key for product table
        tests:
          - not_null

      - name: order_date
        description: order date
        tests:
          - not_null

  - name: bronze_payments
    descripiton: dim table for payment

    columns:
      - name: payment_id
        description: primary for the payment table
        tests:
          - unique:
              config:
                severity: warn
                warn_if: ">10"
          - not_null

      - name: order_id
        description: foreign key for order table for which payment is made
        tests:
          - not_null

      - name: payment_method
        description: represents way through which payment is done like credit/debit/upi
        tests:
          - not_null
          - accepted_values:
              values: ['debit','credit','upi','cash']

      - name: status
        description: status of the payment (fail or success)
        tests:
          - not_null
          - accepted_values:
              values: ['fail','success']

  - name: fct_order_detail
    description: intermediate model for order details
    columns:
      - name: order_id
        description: primary key for the order
        tests:
          - unique:
              config:
                severity: warn
                warn_if: ">10"
          - not_null
      - name: customer_id
        description: primary key for the customer
        tests:
          - not_null
      - name: product_id
        description: primary key for the product 
        tests:
          - not_null
      - name: order_date
        description: order date
        tests:
          - not_null
      - name: price
        description: Price of the product
        tests:
          - not_null
  
  - name: fct_payment_details
    description: Intermediate model for payment details

    columns:
      - name: payment_id
        description: primary key for the payment dim table
        tests:
          - not_null
        
      - name: payment_method
        description: payment method from payment dim table
        tests:
          - not_null

      - name: order_id
        description: order id
        tests:
          - not_null

  - name: product_sales
    description: Final fact table representing total sales amount for a customer

    columns:
      - name: customer_id
        description: primary key for the customer dimension
        tests:
          - not_null

      - name: order_amount
        description: Total order amount.
        tests:
          - not_null
