version: 2

sources:
  - name: dfs_stage
    description: staging source in the snowflake schema
    database: insight_dev
    schema: ins_bkp
    tables:
      - name: ext_chrg_info
        description: Source table for Charging info
        columns:
          - name: run_dt
            description: run date for the table
          - name: division
            description: division
          - name: value
            description: contains variant columns capturing all the columns

      - name: ext_dvsn
        description: Source table for division info
        columns:
          - name: run_dt
            description: run date for the table
          - name: division
            description: division
          - name: value
            description: contains variant columns capturing all the columns

      - name: ext_lcl_crrncy
        description: Source table for LOCAL_CURRENCY info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_pos_shop
        description: Source table for posh shop info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_pos_trmnl
        description: Source table for pos terminal info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_pos_dscnt
        description: Source table for pos dscnt info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_pos_tndr
        description: Source table for pos tndr info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_pos_tx
        description: Source table for pos tx info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_pos_tx_dct
        description: Source table for pos tx dscnt info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_pos_tx_ln
        description: Source table for pos tx line info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_rfnd_tx_rf
        description: Source table for pos refund original tx refernce info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_tndr_type
        description: Source table for tndr type info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_tx_type
        description: Source table for tx type info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: STORE
        description: Store fact table
      - name: CLSFCTN_VLU
        description: CLSFCTN_VLU fact table
      - name: RSKU_VRNT
        description: RSKU_VRNT fact table
      - name: CSKU
        description: CSKU fact table
      - name: RSKU
        description: RSKU fact table
      - name: ORDR_HDR
        description: ORDR_HRDR fact table
      - name: EMPLYMNT_PSTN
        description: EMPLYMNT_PSTN fact table
      - name: NTNLTY
        description: NTNLTY fact table
      - name: CRRNCY
        description: CRRNCY fact table
      - name: TX_HR
        description: TX_HR fact table
      - name: DVSN
        description: Division fact table     
      - name: POS_SHOP
        description: POS_SHOP fact table  