version: 2

sources:
  - name: dfs_stage
    description: staging source in the snowflake schema
    database: external_db
    schema: stage
    tables:
      - name: ext_chrg_info
        description: Source table for Charging info
        columns:
          - name: run_dt
            description: run date for the table
          - name: division
            description: division
          - name: value
            description: contains variant columns capturing all the columns


      - name: ext_dvsn
        description: Source table for division info
        columns:
          - name: run_dt
            description: run date for the table
          - name: division
            description: division
          - name: value
            description: contains variant columns capturing all the columns

      - name: ext_lcl_crrncy
        description: Source table for LOCAL_CURRENCY info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_pos_shop
        description: Source table for posh shop info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns

      - name: ext_pos_trmnl
        description: Source table for pos terminal info
        columns:
          - name: RUN_DT
            description: run date for the table
          - name: DIVISION
            description: division
          - name: VALUE
            description: contains variant columns capturing all the columns


