default:
    outputs:

      dev:
        account:  OEGXSYF-RACKSPACE_PARTNER
        database: DFS_POC_DB
        password: Sattu@1998
        role: DATA_ENG
        schema: P_DATA
        threads: 1
        type: snowflake
        user: satyamkumar
        warehouse: dev_poc_wh
    target: dev
