default:
    outputs:

      dev:
        account:  cv97759-dfs
        database: insight_dev
        password: baba_BOBBY1988
        role: INSIGHT_DEV_USER
        schema: INS_BKP
        threads: 1
        type: snowflake
        user: agnit.chatterjee@dfs.com
        warehouse: WH_INSIGHT_NONPROD_SYSTM_ETL
    target: dev
